Update build-kernel-redbull.yml

diff --git a/.github/workflows/build-kernel-redbull.yml b/.github/workflows/build-kernel-redbull.yml
--- a/.github/workflows/build-kernel-redbull.yml
+++ b/.github/workflows/build-kernel-redbull.yml
@@ -52,24 +52,24 @@ jobs:
           sudo apt update
           sudo apt install build-essential flex bison libssl-dev libelf-dev libncurses5-dev gcc-aarch64-linux-gnu make
 
-      - name: Clone AnyKernel3 and Other Dependencies
-        run: |
-          echo "Cloning AnyKernel3 and other dependencies..."
+      # - name: Clone AnyKernel3 and Other Dependencies
+      #   run: |
+      #     echo "Cloning AnyKernel3 and other dependencies..."
     
-          # Define the branch names using the matrix values
-          ANYKERNEL_BRANCH="android-4.19"
-          SUSFS_BRANCH="kernel-4.19"
+      #     # Define the branch names using the matrix values
+      #     ANYKERNEL_BRANCH="android-4.19"
+      #     SUSFS_BRANCH="kernel-4.19"
 
-          # Debug print the branches
-          echo "Using branch for AnyKernel3: $ANYKERNEL_BRANCH"
-          echo "Using branch for SUSFS: $SUSFS_BRANCH"
+      #     # Debug print the branches
+      #     echo "Using branch for AnyKernel3: $ANYKERNEL_BRANCH"
+      #     echo "Using branch for SUSFS: $SUSFS_BRANCH"
 
-          # Clone repositories using the branch names
-          git clone https://github.com/WildPlusKernel/AnyKernel3.git -b "$ANYKERNEL_BRANCH"
-          git clone https://gitlab.com/simonpunk/susfs4ksu.git -b "$SUSFS_BRANCH"
-          git clone https://github.com/DNNDHH/kernel_patches.git
+      #     # Clone repositories using the branch names
+      #     git clone https://github.com/WildPlusKernel/AnyKernel3.git -b "$ANYKERNEL_BRANCH"
+      #     git clone https://gitlab.com/simonpunk/susfs4ksu.git -b "$SUSFS_BRANCH"
+      #     git clone https://github.com/DNNDHH/kernel_patches.git
 
-      - run: ls -l
+      # - run: ls -l
 
       - name: 🔍 Locate ramdisk
         id: locate_ramdisk
@@ -112,82 +112,82 @@ jobs:
           cp -fv vendor_ramdisk prebuilts/boot-artifacts/ramdisks/vendor_ramdisk-redfin.img
           cp -fv vendor_ramdisk prebuilts/boot-artifacts/ramdisks/vendor_ramdisk-bramble.img
 
-      - name: Add KernelSU
-        run: |
-          echo "Changing to configuration directory: $CONFIG..."
-          cd "$CONFIG/private/msm-google/"
+      # - name: Add KernelSU
+      #   run: |
+      #     echo "Changing to configuration directory: $CONFIG..."
+      #     cd "$CONFIG/private/msm-google/"
           
-          COMMIT_ID="7b0944645172"
-          if git rev-parse --quiet --verify "$COMMIT_ID^{commit}"; then
-              echo "✅ Found commit $COMMIT_ID, checking out..."
-              git checkout $COMMIT_ID
-          else
-              echo "⚠️ Commit $COMMIT_ID not found, skipping checkout."
-          fi
+      #     COMMIT_ID="7b0944645172"
+      #     if git rev-parse --quiet --verify "$COMMIT_ID^{commit}"; then
+      #         echo "✅ Found commit $COMMIT_ID, checking out..."
+      #         git checkout $COMMIT_ID
+      #     else
+      #         echo "⚠️ Commit $COMMIT_ID not found, skipping checkout."
+      #     fi
           
-          echo "Adding KernelSU..."
-          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v0.9.5
-          #cd ./KernelSU/kernel
-          #sed -i 's/ccflags-y += -DKSU_VERSION=16/ccflags-y += -DKSU_VERSION=12321/' ./Makefile
+      #     echo "Adding KernelSU..."
+      #     curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v0.9.5
+      #     #cd ./KernelSU/kernel
+      #     #sed -i 's/ccflags-y += -DKSU_VERSION=16/ccflags-y += -DKSU_VERSION=12321/' ./Makefile
 
-      - name: Apply SUSFS Patches
-        run: |
-          echo "Changing to configuration directory: $CONFIG..."
-          cd "$CONFIG/private/msm-google/"
+      # - name: Apply SUSFS Patches
+      #   run: |
+      #     echo "Changing to configuration directory: $CONFIG..."
+      #     cd "$CONFIG/private/msm-google/"
           
-          echo "Applying SUSFS patches..."
+      #     echo "Applying SUSFS patches..."
           
-          # Copy SUSFS patches
-          cp ../../../susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./KernelSU/
-          cp ../../../susfs4ksu/kernel_patches/50_add_susfs_in_kernel-4.19.patch ./
-          cp ../../../susfs4ksu/kernel_patches/fs/* ./fs/
-          cp ../../../susfs4ksu/kernel_patches/include/linux/* ./include/linux/
+      #     # Copy SUSFS patches
+      #     cp ../../../susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./KernelSU/
+      #     cp ../../../susfs4ksu/kernel_patches/50_add_susfs_in_kernel-4.19.patch ./
+      #     cp ../../../susfs4ksu/kernel_patches/fs/* ./fs/
+      #     cp ../../../susfs4ksu/kernel_patches/include/linux/* ./include/linux/
 
-          cd ./KernelSU
+      #     cd ./KernelSU
           
-          # Apply SUSFS patch for KernelSU
-          patch -p1 --fuzz=3 < 10_enable_susfs_for_ksu.patch || true
+      #     # Apply SUSFS patch for KernelSU
+      #     patch -p1 --fuzz=3 < 10_enable_susfs_for_ksu.patch || true
           
-          # Change to common directory and apply SUSFS patch
-          cd ..
-          patch -p1 --fuzz=3 < 50_add_susfs_in_kernel-4.19.patch || true
+      #     # Change to common directory and apply SUSFS patch
+      #     cd ..
+      #     patch -p1 --fuzz=3 < 50_add_susfs_in_kernel-4.19.patch || true
 
-      - name: Apply KSU Hooks
-        run: |
-          echo "Changing to configuration directory: $CONFIG..."
-          cd "$CONFIG/private/msm-google/"
-          # Apply additional patch
-          cp ../../../kernel_patches/ksu_hooks_4.19.patch ./
-          patch -p1 --fuzz=3 < ./ksu_hooks_4.19.patch
+      # - name: Apply KSU Hooks
+      #   run: |
+      #     echo "Changing to configuration directory: $CONFIG..."
+      #     cd "$CONFIG/private/msm-google/"
+      #     # Apply additional patch
+      #     cp ../../../kernel_patches/ksu_hooks_4.19.patch ./
+      #     patch -p1 --fuzz=3 < ./ksu_hooks_4.19.patch
 
-      - name: Add SUSFS Configuration Settings
-        run: |
-          echo "Changing to configuration directory: $CONFIG..."
-          cd "$CONFIG/private/msm-google/"
+      # - name: Add SUSFS Configuration Settings
+      #   run: |
+      #     echo "Changing to configuration directory: $CONFIG..."
+      #     cd "$CONFIG/private/msm-google/"
           
-          echo "Adding configuration settings to redbull-gki_defconfig..."
+      #     echo "Adding configuration settings to redbull-gki_defconfig..."
           
-          # Add SUSFS configuration settings
-          echo "CONFIG_KSU=y" >> ./arch/arm64/configs/redbull-gki_defconfig
-          echo "CONFIG_KSU_SUSFS=y" >> ./arch/arm64/configs/redbull-gki_defconfig
-          echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> ./arch/arm64/configs/redbull-gki_defconfig
-          echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> ./arch/arm64/configs/redbull-gki_defconfig
-          echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> ./arch/arm64/configs/redbull-gki_defconfig
-          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> ./arch/arm64/configs/redbull-gki_defconfig
-          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> ./arch/arm64/configs/redbull-gki_defconfig
-          echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> ./arch/arm64/configs/redbull-gki_defconfig
-          echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=y" >> ./arch/arm64/configs/redbull-gki_defconfig
-          echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> ./arch/arm64/configs/redbull-gki_defconfig
-          echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> ./arch/arm64/configs/redbull-gki_defconfig
-          echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> ./arch/arm64/configs/redbull-gki_defconfig
-          echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> ./arch/arm64/configs/redbull-gki_defconfig
-          echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> ./arch/arm64/configs/redbull-gki_defconfig
-          echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> ./arch/arm64/configs/redbull-gki_defconfig
-          echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> ./arch/arm64/configs/redbull-gki_defconfig
-          echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> ./arch/arm64/configs/redbull-gki_defconfig
+      #     # Add SUSFS configuration settings
+      #     echo "CONFIG_KSU=y" >> ./arch/arm64/configs/redbull-gki_defconfig
+      #     echo "CONFIG_KSU_SUSFS=y" >> ./arch/arm64/configs/redbull-gki_defconfig
+      #     echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> ./arch/arm64/configs/redbull-gki_defconfig
+      #     echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> ./arch/arm64/configs/redbull-gki_defconfig
+      #     echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> ./arch/arm64/configs/redbull-gki_defconfig
+      #     echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> ./arch/arm64/configs/redbull-gki_defconfig
+      #     echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> ./arch/arm64/configs/redbull-gki_defconfig
+      #     echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> ./arch/arm64/configs/redbull-gki_defconfig
+      #     echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=y" >> ./arch/arm64/configs/redbull-gki_defconfig
+      #     echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> ./arch/arm64/configs/redbull-gki_defconfig
+      #     echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> ./arch/arm64/configs/redbull-gki_defconfig
+      #     echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> ./arch/arm64/configs/redbull-gki_defconfig
+      #     echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> ./arch/arm64/configs/redbull-gki_defconfig
+      #     echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> ./arch/arm64/configs/redbull-gki_defconfig
+      #     echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> ./arch/arm64/configs/redbull-gki_defconfig
+      #     echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> ./arch/arm64/configs/redbull-gki_defconfig
+      #     echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> ./arch/arm64/configs/redbull-gki_defconfig
           
-          # Add additional tmpfs config setting
-          echo "CONFIG_TMPFS_XATTR=y" >> ./arch/arm64/configs/redbull-gki_defconfig
+      #     # Add additional tmpfs config setting
+      #     echo "CONFIG_TMPFS_XATTR=y" >> ./arch/arm64/configs/redbull-gki_defconfig
 
       - name: Run sed and perl Commands
         run: |
@@ -216,31 +216,31 @@ jobs:
           echo "Building the kernel..."
           BUILD_AOSP_KERNEL=1 ./build_redbull-gki.sh
 
-      - name: Create Bootimgs Folder and Copy Images
-        run: |
-          echo "Changing to configuration directory: $CONFIG..."
-          cd "$CONFIG"
+      # - name: Create Bootimgs Folder and Copy Images
+      #   run: |
+      #     echo "Changing to configuration directory: $CONFIG..."
+      #     cd "$CONFIG"
           
-          echo "Copying Image"
-          cp -r ./out/android-msm-pixel-4.19/dist/Image.lz4 ../AnyKernel3/Image
+      #     echo "Copying Image"
+      #     cp -r ./out/android-msm-pixel-4.19/dist/Image.lz4 ../AnyKernel3/Image
           
           
-      - name: Create ZIP Files for Different Formats
-        run: |
-          echo "Creating zip files for all formats..."
-          cd ./AnyKernel3
+      # - name: Create ZIP Files for Different Formats
+      #   run: |
+      #     echo "Creating zip files for all formats..."
+      #     cd ./AnyKernel3
           
-          ZIP_NAME="PIXEL-5-A14-KernelSU-SUSFS.zip"
-          echo "Creating zip file $ZIP_NAME..."
-          zip -r "../$ZIP_NAME" ./*
+      #     ZIP_NAME="PIXEL-5-A14-KernelSU-SUSFS.zip"
+      #     echo "Creating zip file $ZIP_NAME..."
+      #     zip -r "../$ZIP_NAME" ./*
 
           
-      - name: AnyKernel3.zip
-        uses: actions/upload-artifact@v4
-        with:
-          name: AnyKernel3
-          path: |
-            *.zip
+      # - name: AnyKernel3.zip
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: AnyKernel3
+      #     path: |
+      #       *.zip
             
 
       - name: boot.img
